version: "3.8"

services:
  db_dj:
    image: postgres:15
    restart: always
    env_file:
      - ./.env/dev.env
    ports:
      - 5435:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - main

  dj_backend:
    restart: always
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    container_name: dj_backend
    command: >
      sh -c "cd /app/backend &&
      python manage.py makemigrations book &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8011"
    volumes:
      - .:/app
    ports:
      - "8011:8011"
    depends_on:
      - db_dj
    env_file:
      - ./.env/dev.env
    networks:
      - main

networks:
  main:
volumes:
  pgdata:
